### ISSUE TITLE
Crash on load

### ISSUE THREAD

**Issue by irwiss** [irwiss/astroblaze#52]
```
2021-07-11 23:01:38.772 5855-7399/com.astroblaze E/FMQ: grantorIdx must be less than 3
2021-07-11 23:01:38.779 5855-7395/com.astroblaze I/chatty: uid=10303(com.astroblaze) identical 1 line
2021-07-11 23:01:38.781 5855-5998/com.astroblaze E/FMQ: grantorIdx must be less than 3
2021-07-11 23:01:38.781 5855-7395/com.astroblaze I/hw-BpHwBinder: onLastStrongRef automatically unlinking death recipients
2021-07-11 23:01:38.794 5855-7402/com.astroblaze I/CCodec: Created component [c2.android.vorbis.decoder]
2021-07-11 23:01:38.799 5855-7402/com.astroblaze I/CCodecConfig: query failed after returning 7 values (BAD_INDEX)
2021-07-11 23:01:38.806 5855-7402/com.astroblaze W/Codec2Client: query -- param skipped: index = 1107298332.
2021-07-11 23:01:38.807 5855-7402/com.astroblaze W/Codec2Client: query -- param skipped: index = 1342179345.
2021-07-11 23:01:38.807 5855-7402/com.astroblaze W/Codec2Client: query -- param skipped: index = 2415921170.
2021-07-11 23:01:38.808 5855-7402/com.astroblaze E/FMQ: grantorIdx must be less than 3
2021-07-11 23:01:38.808 5855-7402/com.astroblaze E/FMQ: grantorIdx must be less than 3
2021-07-11 23:01:38.810 5855-7402/com.astroblaze I/CCodecBufferChannel: [c2.android.vorbis.decoder#542] Created output block pool with allocatorID 16 => poolID 1857 - OK
2021-07-11 23:01:38.813 5855-7402/com.astroblaze E/FMQ: grantorIdx must be less than 3
2021-07-11 23:01:38.825 5855-5998/com.astroblaze E/FMQ: grantorIdx must be less than 3
2021-07-11 23:01:38.855 5855-7399/com.astroblaze I/chatty: uid=10303(com.astroblaze) NDK MediaCodec_ identical 1 line
2021-07-11 23:01:38.857 5855-7399/com.astroblaze I/hw-BpHwBinder: onLastStrongRef automatically unlinking death recipients
2021-07-11 23:01:38.871 5855-7406/com.astroblaze I/CCodec: Created component [c2.android.vorbis.decoder]
2021-07-11 23:01:38.874 5855-7406/com.astroblaze I/CCodecConfig: query failed after returning 7 values (BAD_INDEX)
2021-07-11 23:01:38.877 5855-7406/com.astroblaze W/Codec2Client: query -- param skipped: index = 1107298332.
2021-07-11 23:01:38.878 5855-7406/com.astroblaze W/Codec2Client: query -- param skipped: index = 1342179345.
2021-07-11 23:01:38.878 5855-7406/com.astroblaze W/Codec2Client: query -- param skipped: index = 2415921170.
2021-07-11 23:01:38.879 5855-7406/com.astroblaze E/FMQ: grantorIdx must be less than 3
2021-07-11 23:01:38.880 5855-7406/com.astroblaze E/FMQ: grantorIdx must be less than 3
2021-07-11 23:01:38.881 5855-7406/com.astroblaze I/CCodecBufferChannel: [c2.android.vorbis.decoder#679] Created output block pool with allocatorID 16 => poolID 1858 - OK
2021-07-11 23:01:38.883 5855-7406/com.astroblaze E/FMQ: grantorIdx must be less than 3
2021-07-11 23:01:38.894 5855-5998/com.astroblaze E/FMQ: grantorIdx must be less than 3
2021-07-11 23:01:38.916 5855-7402/com.astroblaze I/hw-BpHwBinder: onLastStrongRef automatically unlinking death recipients
2021-07-11 23:01:38.956 5855-7406/com.astroblaze I/hw-BpHwBinder: onLastStrongRef automatically unlinking death recipients
2021-07-11 23:01:39.919 5855-5855/com.astroblaze I/MainActivity: NavController onDestinationChanged -> com.astroblaze:id/fragmentLoading
2021-07-11 23:01:39.919 5855-5855/com.astroblaze I/MusicController: Set music track to UI
2021-07-11 23:01:39.926 5855-5855/com.astroblaze I/MainActivity: NavController onDestinationChanged -> com.astroblaze:id/fragmentMenu
2021-07-11 23:01:39.926 5855-5855/com.astroblaze I/MusicController: Music track already was UI, skipping.
2021-07-11 23:01:39.995 5855-5855/com.astroblaze I/HiscoresController: submitRank started
2021-07-11 23:01:40.106 5855-7434/com.astroblaze I/PlayerState: Saved state
2021-07-11 23:01:40.110 5855-7434/com.astroblaze I/HiscoresController: submitRank finished
2021-07-11 23:01:41.076 5855-5855/com.astroblaze I/MainActivity: NavController onDestinationChanged -> com.astroblaze:id/fragmentLevelSelect
2021-07-11 23:01:41.076 5855-5855/com.astroblaze I/MusicController: Music track already was UI, skipping.
2021-07-11 23:01:41.290 5855-5855/com.astroblaze I/FragmentLevelSelect: unproject (ray [(2.3590759E-7,90.00001,93.95789):(2.0191294E-8,-0.8558981,-0.5171445)])
2021-07-11 23:01:41.350 5855-7250/com.astroblaze E/AndroidRuntime: FATAL EXCEPTION: GLThread 3511
    Process: com.astroblaze, PID: 5855
    com.badlogic.gdx.utils.GdxRuntimeException: No buffer allocated!
        at com.badlogic.gdx.graphics.glutils.IndexBufferObject.bind(IndexBufferObject.java:182)
        at com.badlogic.gdx.graphics.Mesh.bind(Mesh.java:514)
        at com.badlogic.gdx.graphics.g3d.shaders.BaseShader.render(BaseShader.java:242)
        at com.badlogic.gdx.graphics.g3d.shaders.DefaultShader.render(DefaultShader.java:775)
        at com.badlogic.gdx.graphics.g3d.shaders.BaseShader.render(BaseShader.java:233)
        at com.badlogic.gdx.graphics.g3d.ModelBatch.flush(ModelBatch.java:206)
        at com.badlogic.gdx.graphics.g3d.ModelBatch.end(ModelBatch.java:217)
        at com.astroblaze.Rendering.Scene3D.render(Scene3D.java:271)
        at com.astroblaze.GdxScreens.GameScreen.render(GameScreen.java:35)
        at com.badlogic.gdx.Game.render(Game.java:46)
        at com.astroblaze.AstroblazeGame.render(AstroblazeGame.java:216)
        at com.badlogic.gdx.backends.android.AndroidGraphics.onDrawFrame(AndroidGraphics.java:471)
        at android.opengl.GLSurfaceView$GLThread.guardedRun(GLSurfaceView.java:1577)
        at android.opengl.GLSurfaceView$GLThread.run(GLSurfaceView.java:1272)
2021-07-11 23:01:41.394 5855-5855/com.astroblaze I/PlayerState: Saved state
2021-07-11 23:01:41.399 5855-7250/com.astroblaze I/Process: Sending signal. PID: 5855 SIG: 9
```

**Comment by irwiss** [comment]
Can't reproduce anymore, probably a debugger induced issue
